spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project-deep-api
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true