name: Java CI Test with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_DB_USERNAME: postgres
  TEST_DB_PASSWORD: password
  TEST_DB_NAME: test-project-deep-api
  TEST_DB_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '20' ]
      fail-fast: false

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.TEST_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.TEST_DB_PASSWORD }}
          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test
        env:
          SPRING_PROFILES_ACTIVE: test
          TEST_DB_CONNECTION_URL: jdbc:postgresql://localhost:${{ env.TEST_DB_PORT }}/${{ env.TEST_DB_NAME }}
        run: mvn -B verify --file pom.xml

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
